spring:
  datasource:
    url: jdbc:h2:mem:financedb
    driver-class-name: org.h2.Driver
    username: sa
    password: ""   # H2 default has no password
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
  servlet:
    context-path: /api

# JWT Configuration
jwt:
  secret: mysupersecurelongsecretkeythatismorethan64characterslong1234567890test
  expiration: 86400000

# External APIs
api:
  alpha-vantage:
    base-url: https://www.alphavantage.co/query
    api-key: demo
  coingecko:
    base-url: https://api.coingecko.com/api/v3
  finnhub:
    base-url: https://finnhub.io/api/v1
    api-key: demo

# CORS Configuration
app:
  cors:
    allowed-origins: "http://localhost:3000"
    allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
    allowed-headers: "*"
